/** Generated script + metadata for podcast content */
export type GeneratedPodcastScript = {
  title: string;
  description: string;
  script: string;
  transcript: string;
  vocabularyHighlights: Array<{ word: string; translation: string }>;
  speakerSegments?: Array<{ speaker: 'A' | 'B'; text: string }>;
};

/** Single exercise as generated by AI */
export type GeneratedExercise = {
  questionNumber: number;
  type:
    | 'multiple_choice'
    | 'true_false'
    | 'fill_blank'
    | 'sentence_order'
    | 'open_ended';
  questionText: string;
  options: string[] | null;
  correctAnswer: string;
  explanationText: string;
};

export type GeneratedExercises = {
  exercises: GeneratedExercise[];
};

/** Open-ended answer evaluation result */
export type OpenEndedEvaluation = {
  score: 0 | 1;
  feedback: string;
};

export interface IAIGateway {
  generatePodcastScript(params: {
    targetLanguage: string;
    nativeLanguage: string;
    cefrLevel: string;
    topic: string;
    durationTarget: string;
  }): Promise<GeneratedPodcastScript>;

  generateExercises(params: {
    transcript: string;
    targetLanguage: string;
    nativeLanguage: string;
    cefrLevel: string;
  }): Promise<GeneratedExercises>;

  evaluateOpenEndedAnswer(params: {
    questionText: string;
    expectedAnswer: string;
    studentAnswer: string;
    targetLanguage: string;
    nativeLanguage: string;
    cefrLevel: string;
  }): Promise<OpenEndedEvaluation>;
}
